RESPONSE_CODE = "ResponseCode"
SUCCESS_CODE = '0'
UNSUCCESS_CODE = '1'
RESPONSE_MESSAGE = 'response'
RESPONSE_UNSUCCESS_MESSAGE ="Invalid"
RESPONSE_SUCCESS_MESSAGE ="Ok"

ERROR_DETAILS ="error"
NO_USER="No such user"
INTERNAL_SERVER_ERROR = "Oops! Something went wrong."
NO_REQUEST_BODY = "Body can not be blank."
REFERENCE_ID = "referenceId"

DATA ="data"



UNSUCCESS_JSON = {
    RESPONSE_CODE: UNSUCCESS_CODE,
    RESPONSE_MESSAGE: RESPONSE_UNSUCCESS_MESSAGE
}

INTERNAL_SERVER_ERROR_JSON = {
    RESPONSE_CODE: UNSUCCESS_CODE,
    RESPONSE_MESSAGE: INTERNAL_SERVER_ERROR
}

SUCCESS_JSON = {
    RESPONSE_CODE: SUCCESS_CODE,
    RESPONSE_MESSAGE: RESPONSE_SUCCESS_MESSAGE
}

BODY_NOT_BLANK_JSON = {
        RESPONSE_CODE: UNSUCCESS_CODE,
        RESPONSE_MESSAGE:"body can not be blank.",
}
